import assert from 'node:assert/strict';
import {GameAudio} from '../dist/game-audio.js';
import {defaults} from '../dist/controls.js';
const param=()=>({value:0,setValueAtTime(){},exponentialRampToValueAtTime(){},setTargetAtTime(v){this.value=v;}});
let scheduled=[],utterances=[],cleared=0,interval;
class Context{constructor(){this.state='running';this.currentTime=0;this.destination={};}resume(){this.state='running';return Promise.resolve();}createGain(){return{gain:param(),connect(){},disconnect(){}};}createBufferSource(){return{connect(){},disconnect(){},start(t,offset=0){scheduled.push({t,offset});},stop(){}};}}
const settings=defaults(),env={AudioContext:Context,setInterval:fn=>{interval=fn;return 1;},clearInterval:()=>cleared++,SpeechSynthesisUtterance:class{constructor(text){this.text=text;}},speechSynthesis:{speaking:false,getVoices:()=>[{name:'Moira',voiceURI:'moira',lang:'en-IE',localService:true}],speak:u=>utterances.push(u),cancel(){}}};
const music=new GameAudio(()=>settings,env);music.tracks.set('arena',{duration:60});music.tracks.set('hunt',{duration:80});music.sync('arena');assert.equal(scheduled.length,0);music.unlock();music.sync('arena');assert.ok(scheduled.length>0);assert.equal(music.mode,'arena');const count=scheduled.length;music.sync('arena');assert.equal(scheduled.length,count);music.context.currentTime=12;music.sync(null);assert.equal(music.offsets.get('arena'),12);music.sync('arena');assert.equal(scheduled.at(-1).offset,12);assert.equal(music.trackSource.loop,true);music.sync('hunt');assert.equal(music.mode,'hunt');music.sync(null);assert.equal(music.mode,null);assert.equal(music.nodes.size,0);assert.equal(music.bus.gain.value,0);
console.log('PASS recorded music requires unlock, loops one source, resumes from its paused position and stops on pause');
music.sync('arena');assert.equal(music.speak('Pass us the butter!!'),true);const first=utterances.at(-1);assert.equal(first.voice.voiceURI,'moira');first.onstart();assert.equal(music.duck,.28);music.speak('Clogs on, Game on!',{force:true});const next=utterances.at(-1);next.onstart();first.onerror();assert.equal(music.duck,.28);next.onend();assert.equal(music.duck,1);settings.voiceVolume=0;const n=utterances.length;assert.equal(music.speak('Muted'),false);assert.equal(utterances.length,n);settings.voiceVolume=.85;music.speak('Good spud');music.stopVoice();assert.equal(music.duck,1);settings.music=false;music.sync('arena');assert.equal(music.mode,null);
console.log('PASS Moira-only voice selection, music ducking, stale speech callback guards and independent muting');
let clock=Date.now()+35000;env.performance={now:()=>clock};music.stopVoice();assert.equal(music.speak('Spud'),true);music.stopVoice();assert.equal(music.speak('Baked'),false);clock+=35000;assert.equal(music.speak('Spud'),false);assert.equal(music.speak('Baked'),true);music.stopVoice();assert.equal(music.speak(''),false);assert.equal(music.speak('Test voice',{force:true}),true);music.stopVoice();
console.log('PASS taunts wait at least 22 seconds, never repeat consecutively and the explicit voice test can bypass cooldown');

let resumeCount=0,resolveResume;const pendingResumes=[];class InterruptedContext extends Context{constructor(){super();this.state='interrupted';}resume(){resumeCount++;return new Promise(resolve=>{resolveResume=()=>{this.state='running';resolve();};pendingResumes.push(resolveResume);});}}
const restored=new GameAudio(()=>({...defaults(),musicVolume:.32}),{...env,AudioContext:InterruptedContext});restored.tracks.set('arena',{duration:60});restored.tracks.set('hunt',{duration:80});restored.sync('arena');restored.unlock();restored.unlock();assert.equal(resumeCount,2,'an unresolved non-activating attempt must not block the next gesture');assert.equal(restored.mode,null);restored.sync(null);resolveResume();await Promise.resolve();assert.equal(restored.mode,null,'late resume must respect a pause');restored.context.state='suspended';restored.sync('hunt');restored.unlock();resolveResume();await Promise.resolve();assert.equal(restored.mode,'hunt');pendingResumes[0]();await Promise.resolve();assert.equal(restored.mode,'hunt','older promises cannot restore an obsolete music mode');assert.ok(restored.bus.gain.value>=.44,'existing volume preferences receive the louder mix');restored.stopMusic();
console.log('PASS interrupted/suspended audio can retry a blocked resume, follows the latest play state and restores an audible music mix');
let deliver,downloads=0;const deferred=new GameAudio(()=>defaults(),{...env,fetch:async file=>{downloads++;if(file.endsWith('arena-funk.mp3'))return new Promise(r=>deliver=()=>r({ok:true,arrayBuffer:async()=>new ArrayBuffer(1)}));return{ok:false};}});deferred.unlock();deferred.context.decodeAudioData=async()=>({duration:40});deferred.loadAssets();deferred.sync('arena');deferred.sync(null);deliver();for(let i=0;i<12;i++)await Promise.resolve();assert.equal(deferred.trackSource,undefined,'late download cannot start music after pause');assert.equal(deferred.assetJobs.get('music:arena'),'ready');const requests=downloads;deferred.unlock();assert.equal(downloads,requests,'unlocks must not duplicate downloads');deferred.sync('arena');assert.ok(deferred.trackSource?.loop);deferred.sync(null);assert.equal(deferred.nodes.size,0);
console.log('PASS late music downloads respect pause, are cached and start only after playback resumes');
