import assert from 'node:assert/strict';
import {STEP,ROUND_TIME,LEVELS,makeMap,route,movement,slideMove,blocked,segmentCircle,segmentBox,circleContact,boxContact,deadzone} from '../dist/core.js';
let tests=0;function test(name,fn){fn();tests++;console.log('PASS '+name);}
test('a full circuit of levels, escalating maze sizes and 120-second default rounds',()=>{assert.ok(LEVELS.length>=21);assert.equal(ROUND_TIME,120);let last=0;for(const l of LEVELS.filter(l=>l.mode==='race')){assert.ok(l.size>last);last=l.size;}});
test('all main and bonus spawn-to-exit routes fit the actual character collider',()=>{for(const level of LEVELS)for(const bonus of[false,true]){const map=makeMap(level,bonus),path=route(map,map.start,map.exit);assert.ok(path.length>0,level.name);let p={...path[0]};for(const target of path.slice(1)){let len=Math.hypot(target.x-p.x,target.z-p.z);slideMove(p,target.x-p.x,target.z-p.z,map.walls);assert.ok(Math.hypot(target.x-p.x,target.z-p.z)<1e-5,level.name);assert.ok(!blocked(p.x,p.z,.42,map.walls));}}});
test('same movement at 30, 60, 120 and 144 render FPS plus jitter',()=>{const simulate=frames=>{let p={x:0,z:0,vx:0,vz:0},acc=0,ticks=0,n=0;while(ticks<1200){acc+=frames[n++%frames.length];while(acc+1e-10>=STEP&&ticks<1200){const phase=Math.floor(ticks/300)%4;movement(p,[{x:1,z:0},{x:1,z:-1},{x:0,z:0},{x:-1,z:1}][phase],STEP,[]);acc-=STEP;ticks++;}}return p;};const expected=simulate([1/120]);for(const frames of[[1/30],[1/60],[1/144],[.006,.031,.017,.011]])assert.deepEqual(simulate(frames),expected);});
test('diagonal speed is normalized',()=>{let a={x:0,z:0,vx:0,vz:0},b={...a};for(let i=0;i<1200;i++){movement(a,{x:1,z:0},STEP,[]);movement(b,{x:1,z:1},STEP,[]);}assert.ok(Math.abs(a.x-Math.hypot(b.x,b.z))<1e-8);});
test('high-speed movement cannot tunnel through walls and slides along them',()=>{const walls=[{x:2,z:0,w:.1,d:30}];let p={x:0,z:0};slideMove(p,40,3,walls);assert.ok(p.x<1.55);assert.ok(Math.abs(p.z-3)<1e-7);assert.ok(!blocked(p.x,p.z,.42,walls));});
test('fast shots detect both thin walls and players crossed between ticks',()=>{assert.equal(segmentBox(-5,0,5,0,{x:0,z:0,w:.01,d:2}),true);assert.equal(segmentCircle(-5,0,5,0,0,0,.4),true);assert.equal(segmentCircle(-5,1,5,1,0,0,.4),false);});
test('controller radial deadzone removes drift and clamps diagonal sticks',()=>{assert.deepEqual(deadzone(.04,.05),{x:0,z:0});const p=deadzone(1,1);assert.ok(Math.abs(Math.hypot(p.x,p.z)-1)<1e-10);});
test('maps are stable for a given seed',()=>{for(const l of LEVELS)assert.deepEqual(makeMap(l).grid,makeMap(l).grid);});
test('every bonus objective, wherever the seed puts it, is clear and reachable with collision radius',()=>{for(const level of LEVELS){const m=makeMap(level,true);let p=m.toWorld(Math.floor(m.n/2),m.n-3);assert.equal(m.objectives.length,2,level.name);for(const goal of[...m.objectives,m.exit]){const path=route(m,p,goal);assert.ok(path.length>0,level.name);for(const next of path.slice(1)){slideMove(p,next.x-p.x,next.z-p.z,m.walls);assert.ok(Math.hypot(p.x-next.x,p.z-next.z)<1e-6,level.name);}assert.ok(!blocked(p.x,p.z,.42,m.walls));}}});
test('projectiles resolve the earliest contact rather than array order',()=>{const near=circleContact(0,0,10,0,2,0,.5),far=boxContact(0,0,10,0,{x:7,z:0,w:1,d:2});assert.ok(near<far);assert.equal(circleContact(0,0,10,0,2,3,.5),Infinity);assert.equal(boxContact(0,0,10,0,{x:7,z:3,w:1,d:1}),Infinity);});
console.log(`${tests} checks passed.`);
