import assert from 'node:assert/strict';
import {cameraPose,aimPoint,shotVelocity,cylinderContact,cameraHeight,CAMERA_SHOULDER} from '../dist/aiming.js';
import {THROW_DROP} from '../dist/core.js';
import {movePlayer,jump,STEP} from '../dist/core.js';
import {bodyHeight,updateStance} from '../dist/stance.js';
const player=()=>({id:0,x:0,y:0,z:0,yaw:0,pitch:0,vx:0,vy:0,vz:0,grounded:true,respawn:0,runBoost:0});
for(const distance of[1,2,4,11])for(const crouching of[false,true]){const p=player(),enemy={...player(),id:1,z:-distance,crouching};p.yaw=-Math.asin(CAMERA_SHOULDER/distance);p.pitch=Math.atan2((crouching?1.05:1.44)-cameraHeight(p),Math.sqrt(distance*distance-CAMERA_SHOULDER*CAMERA_SHOULDER));const view=cameraPose(p),target=aimPoint(p,view,[p,enemy],[]);assert.ok(Math.abs(target.z+distance)<1);for(const gun of[false,true]){const v=shotVelocity(p,target,gun?62:24,gun),flight=Math.hypot(target.x-v.x,target.z-v.z)/(gun?62:24),end={x:v.x+v.vx*flight,y:v.y+v.vy*flight-(gun?0:THROW_DROP*flight*flight),z:v.z+v.vz*flight};assert.ok(Math.hypot(end.x-target.x,end.y-target.y,end.z-target.z)<1e-6);assert.ok(Number.isFinite(cylinderContact({x:target.x,y:target.y,z:target.z+.01},{x:target.x,y:target.y,z:target.z-.01},enemy,.02)));}}
const p=player(),roof={x:0,z:0,w:3,d:4,base:1.76,h:.3},map={walls:[],platforms:[roof]};p.x=-3;for(let i=0;i<180;i++)movePlayer(p,{x:1,z:0},STEP,map);assert.ok(p.x<-1.8,'standing player stops before low roof');for(let i=0;i<120;i++)movePlayer(p,{x:1,z:0,crouch:true},STEP,map);assert.ok(p.x>-1.8);assert.equal(jump(p),false);updateStance(p,false,map.platforms);assert.equal(p.crouching,true,'release cannot stand through ceiling');for(let i=0;i<240;i++)movePlayer(p,{x:1,z:0},STEP,map);assert.equal(p.crouching,false);
const low={...player(),crouching:true};assert.equal(cylinderContact({x:0,y:1.9,z:2},{x:0,y:1.9,z:-2},low),Infinity);assert.ok(Number.isFinite(cylinderContact({x:0,y:1,z:2},{x:0,y:1,z:-2},low)));
console.log('PASS camera-ray targeting at 1/2/4/11m, standing/crouched ballistics, swept hit heights and safe duck-roof movement');
